### ISSUE TITLE
Trigger Voice Recording on Global Hot Key

### ISSUE THREAD

**Issue by chuabingquan** [NatalieTanML/foremcee#3]

**Comment by NatalieTanML** [comment]
actually i just remembered something, should we include some additional preferences like open the app on login (in background)?

**Comment by chuabingquan** [comment]
> actually i just remembered something, should we include some additional preferences like open the app on login (in background)?

That's actually quite a useful feature. Do you think we should slate it for one of the next milestones?

**Comment by NatalieTanML** [comment]
sure

**Comment by chuabingquan** [comment]
Alright, I've opened https://github.com/NatalieTanML/foremcee/issues/7 for us to pickup from after the core features are complete.
